# Generated by Django 6.0 on 2025-12-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stats', to='test_two.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='test_two.task')),
            ],
            options={
                'ordering': ['frequency'],
                'unique_together': {('person', 'task')},
            },
        ),
    ]
