# Generated by Django 6.0 on 2025-12-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['people', '-datetime'], name='test_one_lo_people__67a7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['datetime'], name='test_one_lo_datetim_dc86cf_idx'),
        ),
    ]
